/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.intsuperior.vista;

import ec.edu.intsuperior.controlador.Controlador;

/**
 *
 * @author Nbl
 */
public class Empleado extends javax.swing.JFrame {

    Controlador controlador;
    private Controlador Controlador;
    /**
     * Creates new form Empleado
     */
    public Empleado(Controlador controlador) {
        this.Controlador=controlador;
        initComponents();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        usuario = new javax.swing.JLabel();
        ingresodato = new javax.swing.JTextField();
        usuario1 = new javax.swing.JLabel();
        contraseña = new javax.swing.JPasswordField();
        ingreso = new javax.swing.JButton();
        ingreso2 = new javax.swing.JButton();
        usuario2 = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        usuario.setBackground(new java.awt.Color(51, 0, 51));
        usuario.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        usuario.setForeground(new java.awt.Color(255, 255, 255));
        usuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        usuario.setText("CONTRASEÑA:");
        usuario.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        usuario.setOpaque(true);
        getContentPane().add(usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 200, 90, 30));
        getContentPane().add(ingresodato, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 120, 190, 30));

        usuario1.setBackground(new java.awt.Color(51, 0, 51));
        usuario1.setFont(new java.awt.Font("Cambria Math", 1, 18)); // NOI18N
        usuario1.setForeground(new java.awt.Color(255, 255, 255));
        usuario1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        usuario1.setText("INICIAR SESION COMO EMPLEADO");
        getContentPane().add(usuario1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 30, 320, 30));
        getContentPane().add(contraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 200, 190, 30));

        ingreso.setBackground(new java.awt.Color(102, 0, 102));
        ingreso.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        ingreso.setForeground(new java.awt.Color(255, 255, 255));
        ingreso.setText("INGRESAR");
        ingreso.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ingreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingresoActionPerformed(evt);
            }
        });
        getContentPane().add(ingreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 300, 110, 30));

        ingreso2.setBackground(new java.awt.Color(102, 0, 102));
        ingreso2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        ingreso2.setForeground(new java.awt.Color(255, 255, 255));
        ingreso2.setText("REGRESAR");
        ingreso2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ingreso2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingreso2ActionPerformed(evt);
            }
        });
        getContentPane().add(ingreso2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 300, 120, 30));

        usuario2.setBackground(new java.awt.Color(51, 0, 51));
        usuario2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        usuario2.setForeground(new java.awt.Color(255, 255, 255));
        usuario2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        usuario2.setText("USUARIO:");
        usuario2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        usuario2.setOpaque(true);
        getContentPane().add(usuario2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, 90, 30));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/intsuperior/imagenes/fondo empleado.jpg"))); // NOI18N
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ingresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingresoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ingresoActionPerformed

    private void ingreso2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingreso2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ingreso2ActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Empleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Empleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Empleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Empleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Empleado().setVisible(true);
//            }
//        });
//    }

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField contraseña;
    private javax.swing.JLabel fondo;
    private javax.swing.JButton ingreso;
    private javax.swing.JButton ingreso2;
    private javax.swing.JTextField ingresodato;
    private javax.swing.JLabel usuario;
    private javax.swing.JLabel usuario1;
    private javax.swing.JLabel usuario2;
    // End of variables declaration//GEN-END:variables

}
